ignores:
- akmods-nvidia
- arch-distrobox
- arch-distrobox-amdgpupro
- base
- base-asus
- base-asus-nvidia
- base-framework
- base-main
- base-nokmods
- base-nvidia
- base-surface
- base-surface-nvidia
- bazzite-arch
- boxkit
- config
- experimental
- fedora-distrobox
- gnome-vrr
- images-website
- images-website
- kinoite
- nvidia
- silverblue
- silverblue-experimental
- startingpoint
- ubuntu
- udev-rules
- vauxite
filters:
  tags:
    include:
      - "^[0-9]{2}$"
      - "^[0-9]{2}-(.*)"
      - "^([a-z]+)$"
    exclude:
      - "([0-9]{8})"
      - "\\.sig$"
      - "^pr-.*"
