ignores:
- akmods-nvidia
- base
- bazzite-arch
- boxkit
- config
- experimental
- gnome-vrr
- kinoite
- nvidia
- silverblue
- startingpoint
- ubuntu
- udev-rules
filters:
  tags:
    include:
      - "^[0-9]{2}$"
      - "^[0-9]{2}-(.*)"
      - "^([a-z]+)$"
    exclude:
      - "([0-9]{8})"
      - "\\.sig$"
      - "^pr-.*"
