ignores:
- akmods-nvidia
- base
- base-main
- base-nvidia
- bazzite-arch
- boxkit
- config
- experimental
- gnome-vrr
- kinoite
- nvidia
- silverblue
- silverblue-experimental
- startingpoint
- ubuntu
- udev-rules
- vauxite
filters:
  tags:
    include:
      - "^[0-9]{2}$"
      - "^[0-9]{2}-(.*)"
      - "^([a-z]+)$"
    exclude:
      - "([0-9]{8})"
      - "\\.sig$"
      - "^pr-.*"
