site_name: Universal Blue
repo_name: ublue-os/main
repo_url: https://github.com/ublue-os/main
site_description: Custom Operating System images based on Fedora
site_url: https://universal-blue.org
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate
    - content.tabs.link
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown_include.include:
      base_path: docs
      inheritHeadingDepth: True
  - toc:
      permalink: true
extra:
  analytics:
    provider: google
    property: G-QJBLY50M60
  social:
    - icon: fontawesome/brands/discourse
      link: https://universal-blue.discourse.group
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WEu6BdFEtp
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/JorgeCastro/videos
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@UniversalBlue
    - icon: fontawesome/solid/rss
      link: https://universal-blue.org/feed_rss_updated.xml
plugins:
  search: {}
  redirects: 
      redirect_maps:
        'tinker/make-your-own.md': 'tinker.md'
        'tinker/mindset.md': 'tinker.md'
        'tinker/setup.md': 'tinker.md'
        'tinker/setup/auto-cli.md': 'tinker.md'
        'tinker/setup/auto-web.md': 'tinker.md'
        'tinker/setup/manual.md': 'tinker.md'
        'tinker/installation.md': 'tinker.md'
        'tinker/modification.md': 'tinker.md'
        'tinker/community.md': 'tinker.md'
        'tinker/modules.md': 'tinker.md'
        'tinker/modules/akmods.md': 'tinker.md'
        'tinker/modules/bling.md': 'tinker.md'
        'tinker/modules/default-flatpaks.md': 'tinker.md'
        'tinker/modules/files.md': 'tinker.md'
        'tinker/modules/fonts.md': 'tinker.md'
        'tinker/modules/rpm-ostree.md': 'tinker.md'
        'tinker/modules/script.md': 'tinker.md'
        'tinker/modules/systemd.md': 'tinker.md'
        'tinker/modules/yafti.md': 'tinker.md'
nav:
  - Home: index.md
  - Installation: installation.md
  - Community:
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Discord Chat: https://discord.gg/WEu6BdFEtp
      - Discussion Forums: https://universal-blue.discourse.group/
      - Videos: https://www.youtube.com/c/JorgeCastro/videos
  - Metrics: metrics.md
  - Documentation:
      - Introduction: introduction.md
      - Contributor's Guide:
          - Architecture: architecture.md
          - Contributing: CONTRIBUTING.md
          - Repository Health: contributor-health.md
          - Proposals: https://github.com/orgs/ublue-os/discussions?discussions_q=is%3Aopen+label%3Aproposal
          - Roadmap: https://github.com/orgs/ublue-os/projects/1
      - Tinkerer's Guide (deprecated): tinker.md