site_name: Universal Blue
repo_name: ublue-os/main
repo_url: https://github.com/ublue-os/main
theme:
  name: material
  custom_dir: overrides
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - navigation.footer
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate
    - content.tabs.link
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - markdown_include.include:
      base_path: docs
      inheritHeadingDepth: True
extra:
  analytics:
    provider: google
    property: G-QJBLY50M60
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WEu6BdFEtp
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/JorgeCastro/videos
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/jorge
nav: 
  - Home: index.md
  - Installation: 
    - installation.md
    - Images: images.md
    - Toolboxes: toolboxes.md
  - Community:
    - Code of Conduct: CODE_OF_CONDUCT.md
    - Mission: mission.md
    - Scope: scope.md
    - Values: values.md
  - Documentation:
    - Architecture: architecture.md
    - Make Your Own: making-your-own.md
    - Codecs: codecs.md
  - FAQ: faq.md
  - Contributing: CONTRIBUTING.md
