site_name: Universal Blue
repo_name: ublue-os/main
repo_url: https://github.com/ublue-os/main
site_description: Custom Operating System images based on Fedora
site_url: https://ublue.it
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - announce.dismiss
    - navigation.expand
    - navigation.footer
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 
    - toc.integrate
    - search.highlight
    - search.suggest
    - search.share
    - toc.integrate
    - content.tabs.link
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown_include.include:
      base_path: docs
      inheritHeadingDepth: True
  - toc:
      permalink: true
extra:
  analytics:
    provider: google
    property: G-QJBLY50M60
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/WEu6BdFEtp
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/JorgeCastro/videos
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@jorge
    - icon: fontawesome/solid/rss
      link: https://ublue.it/feed_rss_updated.xml
plugins:
  search: {}
  external-markdown: {}
  mkdocs-video:
      video_muted: True
      video_controls: True
      css_style:
        width: "50%"
        height: "22.172vw"
  git-committers:
      enabled: true
      repository: ublue-os/website
      branch: main
  rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
nav:
  - Home: index.md
  - Installation:
      - installation.md
  - Images:
      - Full Image List: images.md
      - Main Images: images/main.md
      - Nvidia Images: images/nvidia.md
      - Bazzite: images/bazzite.md
      - Bluefin: images/bluefin.md
      - Toolboxes: toolboxes.md
  - Community:
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Discord Chat: https://discord.gg/WEu6BdFEtp
      - Discussion Forums: https://github.com/orgs/ublue-os/discussions
      - Mission: mission.md
      - Scope: scope.md
      - Values: values.md
      - Videos: https://www.youtube.com/c/JorgeCastro/videos
  - Documentation:
      - Introduction: introduction.md
      - User's Guide:
          - Installing Software: guide/software.md
          - just: guide/just.md
          - Toolboxes: guide/toolbox.md
          - Codecs: guide/codecs.md
          - Thumbnails: guide/thumbnails.md
          - Screensharing on Wayland: guide/screensharing.md
      - Contributor's Guide:
          - Architecture: architecture.md
          - Contributing: CONTRIBUTING.md
          - Proposals: https://github.com/orgs/ublue-os/discussions?discussions_q=is%3Aopen+label%3Aproposal
          - Roadmap: https://github.com/orgs/ublue-os/projects/1
      - Tinkerer's Guide:
          - Introduction: tinker/make-your-own.md
          - Mindset: tinker/mindset.md
          - Setup:
            - tinker/setup/index.md
            - Automatic setup (cli): tinker/setup/auto-cli.md
            - Automatic setup (web): tinker/setup/auto-web.md
            - Manual setup: tinker/setup/manual.md
          - Installation: tinker/installation.md
          - Modification: tinker/modification.md
          - Community: tinker/community.md
  - FAQ: faq.md
  - Media: media.md
  - Blog:
      - blog/index.md
