castrojo:
  name: Jorge O. Castro
  description: Contributor
  avatar: https://github.com/castrojo.png
bsherman:
  name: Benjamin Sherman
  description: Contributor
  avatar: https://github.com/bsherman.png
KyleGospo:
  name: Kyle Gospo
  description: Contributor
  avatar: https://github.com/KyleGospo.png
EyeCantCU:
  name: RJ Trujillo
  description: Contributor
  avatar: https://github.com/EyeCantCU.png
nicknamenamenick:
  name: nicknamenick
  description: Contributor
  avatar: https://github.com/nicknamenamenick.png
xynydev:
  name: xyny
  description: Contributor
  avatar: https://github.com/xynydev.png
