castrojo:
  name: Jorge O. Castro
  description: Contributor
  avatar: https://github.com/castrojo.png
bsherman:
  name: Benjamin Sherman
  description: Contributor
  avatar: https://github.com/bsherman.png
